kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
       smtp_smarthost: 'smtp.126.com:25'
       smtp_from: 'cecii8@126.com'
       smtp_auth_username: 'cecii8@126.com'
       smtp_auth_password: 'cecii123'
       smtp_require_tls: false
                                
    route:
      repeat_interval: 7m
      receiver: 'email'
    
    receivers:
    - name: 'email'
      email_configs:
      - to: '89338149@qq.com'